site_name: gho
site_description: Gho Backend project
repo_url: https://github.com/othreecodes/gho_backend
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/othreecodes">othreecodes</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
