# Generated by Django 2.1.9 on 2019-09-07 23:42

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_phoneverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserPhoneVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('verification_code', models.CharField(max_length=30)),
                ('is_verified', models.BooleanField(default=False)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'New User Verification Codes',
            },
        ),
    ]
